apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.ingress.name }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  # ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.service.name }}-service
            port:
              number: 8080
    host: {{ .Values.ingress.host }}