apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: {{ .Values.namespace.name }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzd2xpZG9jIiwicGFzc3dvcmQiOiJKZW5raW5zMTIzIiwiZW1haWwiOiJ2aXN3YW5hdGhhbnNoYWxpbjVAZ21haWwuY29tIiwiYXV0aCI6ImMzZHNhV1J2WXpwS1pXNXJhVzV6TVRJeiJ9fX0=
type: kubernetes.io/dockerconfigjson