apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    # - name: maven
    #   image: maven:3.3.9-jdk-8-alpine
    #   command:
    #     - cat
    #   tty: true
    #   volumeMounts:
    #     - name: m2
    #       mountPath: /root/.m2
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      command:
        - cat
      tty: true
    - name: ubuntu
      image: ubuntu:21.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0      
      command:
        - cat
      tty: true
      privileged: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    # - name: m2
    #   hostPath:
    #     path: /root/.m2